import { Geist, Geist_Mono } from "next/font/google";
import "../assets/css/globals.css";
import localFont from "next/font/local";
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";

const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/Satoshi-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Quagnite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // className={satoshi.className}
    <html lang="en">
      <body>
        <Header />
        <main className="ic_bg_pink">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
